# -*- coding: utf-8 -*-
"""Step1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kA56s8KlQKepCjTlAHNMYlbjj7zLoW_G

# LifeSnaps Pre-Processing

This notebook extracts and cleans wearable-derived features from the
LifeSnaps Fitbit BSON dump (Yfantidou et al., *Sci. Data* 9, 663, 2022, https://www.nature.com/articles/s41597-022-01764-x)
for downstream stress-physiology analysis.

**Pipeline.**
1. Decode `fitbit.bson` once into per-collection Parquet files (chunked).
2. For each modality (sleep, temperature, heart rate, SpO2, steps,
   respiratory rate, VO2max, HRV, demographics) load the corresponding
   Parquet, clean it, and write a tidy output for downstream analysis.

## Configuration

Edit `RAW_DIR` and `OUT_DIR` to point at your local copies. The raw
LifeSnaps BSON dump is expected at `RAW_DIR/fitbit.bson`.
"""

import os
from collections import defaultdict
from pathlib import Path

import bson
import numpy as np
import pandas as pd

# Input: directory containing the LifeSnaps `fitbit.bson` dump.
RAW_DIR = Path("/content/drive/My Drive/LifeSnaps/raw")
BSON_FILE = RAW_DIR / "fitbit.bson"

# Intermediate: per-collection Parquet files extracted from BSON.
PARQUET_DIR = RAW_DIR / "fitbit_parquet_files"
PARQUET_DIR.mkdir(parents=True, exist_ok=True)

# Output: cleaned, per-modality Parquet files used by downstream notebooks.
OUT_DIR = Path("/content/drive/My Drive/LifeSnaps/processed")
(OUT_DIR / "Sleep").mkdir(parents=True, exist_ok=True)
(OUT_DIR / "HR").mkdir(parents=True, exist_ok=True)
(OUT_DIR / "HRV").mkdir(parents=True, exist_ok=True)
(OUT_DIR / "PostDataset").mkdir(parents=True, exist_ok=True)

"""## 1. BSON to Parquet (one-time extraction)

Decode `fitbit.bson` once and write one Parquet per collection. Documents
are buffered in `CHUNK_SIZE` batches and appended via read-modify-write
to avoid loading the whole document stream into memory.
"""

CHUNK_SIZE = 250_000


def write_chunk_to_parquet(data_dict, out_dir):
    """Append each per-collection chunk to its Parquet file."""
    for table_name, records in data_dict.items():
        if not records:
            continue
        new_df = pd.json_normalize(records)

        # The Profile collection encodes some BMI values as e.g. "<18.5".
        if table_name == "Profile" and "bmi" in new_df.columns:
            new_df["bmi"] = pd.to_numeric(
                new_df["bmi"].astype(str).str.replace("<", ""),
                errors="coerce",
            )

        safe_name = "".join(c for c in table_name if c.isalnum() or c in "_-")
        out_path = out_dir / f"fitbit_{safe_name}.parquet"

        if out_path.exists():
            existing_df = pd.read_parquet(out_path)
            combined_df = pd.concat([existing_df, new_df], ignore_index=True)
            combined_df.to_parquet(out_path, index=False)
        else:
            new_df.to_parquet(out_path, index=False)
        print(f"  wrote {len(records):>8} records -> {out_path.name}")
    data_dict.clear()


def extract_bson(bson_path, out_dir, chunk_size=CHUNK_SIZE):
    """Stream `bson_path`, grouping documents by `type` into Parquet files."""
    records_chunk = defaultdict(list)
    doc_count = 0
    with open(bson_path, "rb") as f:
        for doc in bson.decode_file_iter(f):
            doc_type = doc.get("type")
            user_id = doc.get("id")
            data_object = doc.get("data", {})
            if not (doc_type and data_object):
                continue
            data_object["id"] = str(user_id)
            records_chunk[doc_type].append(data_object)
            doc_count += 1
            if doc_count >= chunk_size:
                print(f"Flushing {doc_count} buffered documents...")
                write_chunk_to_parquet(records_chunk, out_dir)
                doc_count = 0
    print("Flushing final buffered documents...")
    write_chunk_to_parquet(records_chunk, out_dir)
    print("BSON extraction complete.")


extract_bson(BSON_FILE, PARQUET_DIR)

"""### Sanity check: unique participant IDs per collection"""

for path in sorted(PARQUET_DIR.glob("*.parquet")):
    df = pd.read_parquet(path)
    if "id" in df.columns:
        print(f"{path.name:60s} unique ids = {df['id'].nunique()}")
    else:
        print(f"{path.name:60s} (no 'id' column)")

"""## 2. Sleep

Explode the nested `levels.data` field into one row per sleep stage
segment, scale duration to seconds (raw values are reported in
deciseconds), and write one `Sleep.parquet` per participant.
"""

df_sleep = pd.read_parquet(PARQUET_DIR / "fitbit_sleep.parquet")

for uid, grp in df_sleep.groupby("id"):
    records = grp["levels.data"].explode().dropna()
    df_levels = (
        pd.DataFrame(list(records))
          .rename(columns={"dateTime": "datetime",
                           "seconds":  "Value",
                           "level":    "Type"})
    )
    df_levels["Value"] = df_levels["Value"] / 10  # deciseconds -> seconds

    user_dir = OUT_DIR / "Sleep" / str(uid)
    user_dir.mkdir(parents=True, exist_ok=True)
    df_levels[["datetime", "Value", "Type"]].to_parquet(
        user_dir / "Sleep.parquet", index=False,
    )
    print(f"{uid}: {len(df_levels)} stage rows")

"""## 3. Nocturnal temperature

Compute median skin temperature within each sleep window. Two source
tables are joined: `ComputedTemperature` provides per-night sleep
windows (`sleep_start`, `sleep_end`); `temperature` provides timestamped
device readings (`recorded_time`, `temperature`). Implausible nightly
deviations (|deltaT| > 3 C) are dropped.
"""

df_temp = pd.read_parquet(PARQUET_DIR / "fitbit_ComputedTemperature.parquet")
df_temp_dev = pd.read_parquet(PARQUET_DIR / "fitbit_temperature.parquet")

df_temp = (
    df_temp[["id", "sleep_start", "sleep_end", "nightly_temperature"]]
      .drop_duplicates(subset=["id", "sleep_start", "nightly_temperature"])
)

df_temp["sleep_start"] = pd.to_datetime(df_temp["sleep_start"], format="ISO8601")
df_temp["sleep_end"]   = pd.to_datetime(df_temp["sleep_end"],   format="ISO8601")
df_temp_dev["recorded_time"] = pd.to_datetime(df_temp_dev["recorded_time"], format="ISO8601")

merged = pd.merge(df_temp, df_temp_dev, on="id", how="left")
valid_temps = merged[
    merged["recorded_time"].between(merged["sleep_start"], merged["sleep_end"])
]

median_temps = (
    valid_temps
      .groupby(["id", "sleep_start", "sleep_end"])["temperature"]
      .median()
      .reset_index()
      .rename(columns={"temperature": "median_temperature"})
)

final_df_temp = (
    pd.merge(df_temp, median_temps, on=["id", "sleep_start", "sleep_end"], how="left")
      .query("median_temperature >= -3 and median_temperature <= 3")
      .sort_values(["id", "sleep_start"])
      .rename(columns={"id": "Global_Deidentified"})
)
valid_temps = valid_temps.rename(columns={"id": "Global_Deidentified"})

final_df_temp.to_parquet(OUT_DIR / "PostDataset" / "Temperature.parquet",
                         engine="pyarrow", index=False)
valid_temps.to_parquet(OUT_DIR / "PostDataset" / "Temperature_dev.parquet",
                       engine="pyarrow", index=False)
print(f"Temperature: {len(final_df_temp)} sleep-night rows.")

"""## 4. Resting heart rate

Daily RHR series. Drop missing or zero placeholder values.
"""

df_RHR = pd.read_parquet(PARQUET_DIR / "fitbit_resting_heart_rate.parquet")

df_RHR = (
    df_RHR[["id", "value.date", "value.value"]]
      .rename(columns={"id": "Global_Deidentified",
                       "value.date": "Date",
                       "value.value": "Resting Heart Rate"})
)
df_RHR = df_RHR[df_RHR["Resting Heart Rate"].notna() & (df_RHR["Resting Heart Rate"] != 0)]

df_RHR.to_parquet(OUT_DIR / "PostDataset" / "RHR.parquet",
                  engine="pyarrow", index=False)
print(f"RHR: {len(df_RHR)} rows.")

"""## 5. Heart rate (intraday)

Per-participant intraday HR series, written one `HR.parquet` per
participant for downstream sleep-aligned aggregation.
"""

df_HR = pd.read_parquet(PARQUET_DIR / "fitbit_heart_rate.parquet")

df_HR = (
    df_HR[["dateTime", "id", "value.bpm"]]
      .rename(columns={"dateTime": "datetime",
                       "id": "Global_Deidentified",
                       "value.bpm": "Value"})
)
df_HR["datetime"] = pd.to_datetime(df_HR["datetime"])

hr_dir = OUT_DIR / "HR"
for id_val, grp in df_HR.groupby("Global_Deidentified"):
    user_dir = hr_dir / str(id_val)
    user_dir.mkdir(parents=True, exist_ok=True)
    grp[["datetime", "Value"]].to_parquet(user_dir / "HR.parquet", index=False)
print(f"HR: wrote {df_HR['Global_Deidentified'].nunique()} per-participant files.")

"""## 6. Daily SpO2"""

df_spO2 = pd.read_parquet(PARQUET_DIR / "fitbit_DailySpO2.parquet")

df_spO2 = (
    df_spO2[["timestamp", "id", "average_value"]]
      .rename(columns={"timestamp": "datetime",
                       "id": "Global_Deidentified",
                       "average_value": "Value"})
)
df_spO2["datetime"] = pd.to_datetime(df_spO2["datetime"])

df_spO2.to_parquet(OUT_DIR / "PostDataset" / "SpO2.parquet",
                   engine="pyarrow", index=False)
print(f"SpO2: {len(df_spO2)} rows.")

"""## 7. Steps

Aggregate intraday step counts to daily totals per participant.
"""

df_steps = pd.read_parquet(PARQUET_DIR / "fitbit_steps.parquet")

df_steps["value"] = (
    pd.to_numeric(df_steps["value"], errors="coerce").fillna(0).astype(int)
)
df_steps["Date"] = pd.to_datetime(df_steps["dateTime"]).dt.date

df_daily = (
    df_steps
      .groupby(["id", "Date"], as_index=False)["value"]
      .sum()
      .rename(columns={"id": "Global_Deidentified",
                       "value": "Total_Number_of_Steps"})
)

df_daily.to_parquet(OUT_DIR / "PostDataset" / "Steps.parquet",
                    engine="pyarrow", index=False)
print(f"Steps: {len(df_daily)} participant-days.")

"""## 8. Respiratory rate

Source values of `-1` are Fitbit's missing-data sentinel and are coerced
to NaN. Some `(id, Date)` pairs appear more than once in the raw data;
duplicates are collapsed by mean per metric.
"""

df_BR = pd.read_parquet(PARQUET_DIR / "fitbit_RespiratoryRateSummary.parquet")

br_cols = [
    "full_sleep_breathing_rate",  "full_sleep_standard_deviation",
    "deep_sleep_breathing_rate",  "deep_sleep_standard_deviation",
    "light_sleep_breathing_rate", "light_sleep_standard_deviation",
    "rem_sleep_breathing_rate",   "rem_sleep_standard_deviation",
]

df_BR["timestamp"] = pd.to_datetime(df_BR["timestamp"])
df_BR["Date"] = df_BR["timestamp"].dt.date
df_BR = df_BR[["Date", "timestamp", "id", *br_cols]].drop_duplicates()

# -1 -> NaN, then collapse same-day duplicates per participant via mean.
df_BR[br_cols] = df_BR[br_cols].apply(pd.to_numeric, errors="coerce").replace(-1, np.nan)
df_BR_avg = (
    df_BR.groupby(["id", "Date"], as_index=False)[br_cols].mean()
         .rename(columns={"id": "Global_Deidentified"})
)

df_BR_avg.to_parquet(OUT_DIR / "PostDataset" / "BR.parquet",
                     engine="pyarrow", index=False)
print(f"Breathing rate: {len(df_BR_avg)} participant-days.")

"""## 9. VO2Max

Retain one VO2Max value per participant per day.
"""

df_VO2MAX = pd.read_parquet(PARQUET_DIR / "fitbit_demographic_vo2_max.parquet")

df_VO2MAX = (
    df_VO2MAX[["id", "dateTime", "value.filteredDemographicVO2Max"]]
      .rename(columns={"id": "Global_Deidentified",
                       "dateTime": "Date",
                       "value.filteredDemographicVO2Max": "Value"})
)
df_VO2MAX["Date"] = pd.to_datetime(df_VO2MAX["Date"]).dt.date
df_VO2MAX = df_VO2MAX.drop_duplicates(subset=["Global_Deidentified", "Date"], keep="first")

df_VO2MAX.to_parquet(OUT_DIR / "PostDataset" / "VO2Max.parquet",
                     engine="pyarrow", index=False)
print(f"VO2Max: {len(df_VO2MAX)} participant-days.")

"""## 10. HRV (deep-sleep, intraday)

The `HeartRateVariabilityDetails` collection provides 5-minute deep-sleep
HRV samples (RMSSD plus low/high-frequency power). Reshape to long form
(`Type` in {`rmssd`, `lf`, `hf`}) and write one `HRV.parquet` per
participant.
"""

df_HRV = pd.read_parquet(PARQUET_DIR / "fitbit_HeartRateVariabilityDetails.parquet")

df_HRV = (
    df_HRV[["id", "timestamp", "rmssd", "low_frequency", "high_frequency"]]
      .rename(columns={"id": "Global_Deidentified",
                       "timestamp": "datetime",
                       "low_frequency": "lf",
                       "high_frequency": "hf"})
)
df_HRV["datetime"] = pd.to_datetime(df_HRV["datetime"])

df_long = df_HRV.melt(
    id_vars=["Global_Deidentified", "datetime"],
    value_vars=["rmssd", "lf", "hf"],
    var_name="Type",
    value_name="Value",
)[["Global_Deidentified", "datetime", "Value", "Type"]]

hrv_dir = OUT_DIR / "HRV"
for id_val, grp in df_long.groupby("Global_Deidentified"):
    user_dir = hrv_dir / str(id_val)
    user_dir.mkdir(parents=True, exist_ok=True)
    grp[["datetime", "Value", "Type"]].to_parquet(user_dir / "HRV.parquet", index=False)
print(f"HRV: wrote {df_long['Global_Deidentified'].nunique()} per-participant files.")

"""## 11. Demographics

Load participant profiles for downstream demographic summaries.
"""

df_profile = pd.read_parquet(PARQUET_DIR / "fitbit_Profile.parquet")
print(f"Profile: {len(df_profile)} participants, columns = {list(df_profile.columns)}")

df_profile.to_parquet(OUT_DIR / "PostDataset" / "fitbit_Profile.parquet",
                      engine="pyarrow", index=False)